import os
import google.generativeai as genai
from typing import Dict

def generate_viral_metadata(transcript: str) -> Dict[str, str]:
    """
    Generates viral title, description, and hashtags based on the transcript using Gemini.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return {
            "title": "Shorts Video",
            "description": "Generated by Local Shorts Generator",
            "hashtags": "#shorts #video"
        }

    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-pro')

        prompt = f"""
        You are a social media expert. Based on the following transcript from a short video, generate:
        1. A catchy, viral Title (max 60 chars).
        2. A compelling Description (max 150 chars).
        3. 5-7 relevant, high-traffic Hashtags.

        Transcript:
        "{transcript}"

        Format your response EXACTLY as follows (no other text):
        Title: [Your Title]
        Description: [Your Description]
        Hashtags: [Your Hashtags]
        """

        response = model.generate_content(prompt)
        text = response.text.strip()
        
        # Parse logic
        lines = text.split('\n')
        title = "Cool Video"
        desc = "Check this out!"
        tags = "#shorts"

        for line in lines:
            if line.startswith("Title:"):
                title = line.replace("Title:", "").strip()
            elif line.startswith("Description:"):
                desc = line.replace("Description:", "").strip()
            elif line.startswith("Hashtags:"):
                tags = line.replace("Hashtags:", "").strip()
        
        return {
            "title": title,
            "description": desc,
            "hashtags": tags
        }

    except Exception as e:
        print(f"Metadata generation failed: {e}")
        return {
            "title": "New Short",
            "description": "Watch this amazing clip!",
            "hashtags": "#shorts #viral #trending"
        }
